config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'complaints#index'

  resources :complaints, except: :destroy
  resources :solicitations, except: :destroy
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
  validates :subject, :complaint_type, :content, presence: true

  TYPES = ['Indisponibilidade de serviço', 'Produtos contratados', 'Qualidade do produto', 'Qualidade do serviço', 'Erro de cobrança', 'Atendimento'].freeze
end

app/models/solicitation.rb
class Solicitation < ActiveRecord::Base
  validates :subject, :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :login_layout

  protected

  def login_layout
    if current_user
      'application'
    else
      'login'
    end
  end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_complaint, only: [:show, :edit, :update]

  def index
    @complaints = Complaint.all
    @solicitations = Solicitation.all
  end

  def new
    @complaint = Complaint.new
  end

  def create
    @complaint = Complaint.create(complaint_params)
    redirect_to complaint_path(@complaint)
  end

  def update
    @complaint.update(complaint_params)
    redirect_to complaint_path(@complaint)
  end

  def show
  end

  def edit
  end

  private

  def set_complaint
    @complaint = Complaint.find(params[:id])
  end

  def complaint_params
    params.require(:complaint)
          .permit(:subject, :complaint_type, :content)
  end
end

app/controllers/solicitations_controller.rb
class SolicitationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_solicitation, only: [:show, :edit, :update]

  def index
    @solicitations = Solicitation.all
  end

  def new
    @solicitation = Solicitation.new
  end

  def create
    @solicitation = Solicitation.create(complaint_params)
    redirect_to solicitation_path(@solicitation)
  end

  def update
    @solicitation.update(complaint_params)
    redirect_to solicitation_path(@solicitation)
  end

  def show
  end

  def edit
  end

  private

  def set_solicitation
    @solicitation = Solicitation.find(params[:id])
  end

  def complaint_params
    params.require(:solicitation)
          .permit(:subject, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/complaints/_complaint.html.erb
<ul class="collection with-header">
  <li class="collection-item active"><h6><%= 'Protocolo da reclamação: ' + complaint.id.to_s %></h6></li>
  <li class="collection-item"><%= complaint.subject %></li>
  <li class="collection-item"><%= complaint.complaint_type %></li>
  <li class="collection-item"><%= complaint.content %></li>
  <li class="collection-item"><%= link_to 'Alterar reclamação', edit_complaint_path(complaint) %></li>
</ul>
<br/>

app/views/complaints/_empty_card.html.erb
<div class="row">
  <div class="card blue-grey darken-1 center-align">
    <div class="card-content white-text">
      <span class="card-title flow-text">Você não possui nenhuma intereção!</span>
      <br/>
      <p class="flow-text"> Ops, percebemos que você não fez nenhuma interação com nosso sistema ainda.</p>
      <p class="flow-text"> Utilize os links abaixo para iniciar uma nova interação.</p>
      <p class="flow-text"> Neste espaço você poderá visualizar todas as suas solicitações e reclamações.</p>
    </div>
    <div class="card-action">
      <%= link_to 'Nova Solicitação', root_path %>
      <%= link_to 'Nova Reclamação', new_complaint_path %>
    </div>
  </div>
</div>

app/views/complaints/_form.html.erb
<%= form_for @complaint do |f| %>
  <div class="input-field">
    <%= f.label :subject, 'Resumo' %>
    <%= f.text_field :subject %>
  </div>
  <div class="input-field">
    <%= f.label :complaint_type, 'Tipo' %>
    <br/>
    <%= f.select :complaint_type, Complaint::TYPES %>
  </div>
  <div class="input-field">
    <%= f.label :content, 'Descreva o problema' %>
    <%= f.text_area :content, class:'materialize-textarea' %>
  </div>
  <div class="input-field center-align">
    <%= f.submit 'Enviar Reclamação', class: 'btn' %>
  </div>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
  $('select').material_select();
});
</script>

app/views/complaints/_notices.html.erb
<h5 class="center-align card-panel red lighten-1 white-text">Notícias importantes</h5>
<ul class="collapsible" data-collapsible="accordion">
  <li>
    <div class="collapsible-header"><i class="material-icons">filter_drama</i>Aviso de indisponibilidade de Serviço</div>
    <div class="collapsible-body"><p>Alguns serviços estarão inoperantes amanhã entre as 2AM e 6AM.</p></div>
  </li>
  <li>
    <div class="collapsible-header"><i class="material-icons">place</i>Regiões afetadas pelas chuvas dos últimos dias</div>
    <div class="collapsible-body">
      <p>Algumas regiões enfrentaram problemas por conta das chuvas, são elas: Vila Nova Jaraguá, Jundiaí, Sol Nascente e Taipas.</p>
    </div>
  </li>
  <li>
    <div class="collapsible-header"><i class="material-icons">whatshot</i>Falha no centro de distribuição</div>
    <div class="collapsible-body"><p>Um backbone central ficou indisponível por 2h na madrugada de ontem, poucos usuários foram afetados.</p></div>
  </li>
</ul>

app/views/complaints/index.html.erb
<%= render partial: 'notices' %>
<h5 class="center-align card-panel red lighten-1 white-text">Minhas reclamações</h5>
<%= render partial: 'empty_card' unless @complaints.any? %>
<% @complaints.each do |complaint| %>
  <%= render partial: complaint %>
<% end %>

<h5 class="center-align card-panel red lighten-1 white-text">Minhas solicitações</h5>
<% @solicitations.each do |solicitation| %>
  <%= render partial: solicitation %>
<% end %>

app/views/complaints/new.html.erb
<h5 class="center-align card-panel red lighten-1 white-text">Nova Reclamação</h5>
<%= render partial: 'form' %>

app/views/complaints/show.html.erb
<%= render @complaint %>

app/views/layouts/_footer.html.erb
<footer class="page-footer blue darken-2">
  <div class="footer-copyright blue darken-2">
    <p class="row center-align white-text container">FATEC 2016</p>
  </div>
</footer>

app/views/layouts/_sidebar.html.erb
<ul class="right hide">
  <li><%= link_to 'Todas as informações', complaints_path %></li>
  <li><%= link_to 'Nova Reclamação', new_complaint_path %></li>
  <li><%= link_to 'Nova Solicitação', new_solicitation_path %></li>
</ul>
<ul id="slide-out" class="side-nav fixed hido-on-med-and-down">
  <%= link_to root_path do %>
    <p class="center-align"><%= image_tag("group-of-people.png", width: '64', height:'64')%></p>
  <% end %>
  <li><%= link_to 'Todas as informações', complaints_path %></li>
  <li><%= link_to 'Nova Reclamação', new_complaint_path %></li>
  <li><%= link_to 'Nova Solicitação', new_solicitation_path %></li>
</ul>
<a href="#" data-activates="slide-out" class="button-collapse show-on-large"><i class="mdi-navigation-menu"></i></a>

<script type="text/javascript">
$('.button-collapse').sideNav('show');
$('.button-collapse').sideNav();
</script>

app/views/layouts/_topbar.html.erb
<nav class="blue darken-2">
  <div class="nav-wrapper container">
    <a href="#" data-activates="slide-out" class="button-collapse hide-on-large-only"><i class="material-icons">menu</i></a>
    <%= link_to 'SAC Solution', root_path, class: 'brand-logo center' %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= current_user.email if current_user %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, 'data-method': 'delete' if current_user %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SAC Solution</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <header>
      <%= render partial: '/layouts/topbar' %>
    </header>
    <main>
    <%= render partial: '/layouts/sidebar' %>
    <div class="row container">
      <div class="col s12 offset-l1">
        <div class="row">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </div>
    </main>
    <footer>
      <%= render partial: '/layouts/footer' %>
    </footer>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SAC Solution</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>
    <header>
      <%= render partial: '/layouts/topbar' %>
    </header>
    <main>
    <div class="row container">
      <div class="col s12">
        <div class="row">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </div>
    </main>
    <footer>
      <%= render partial: '/layouts/footer' %>
    </footer>
  </body>
</html>

app/views/solicitations/_form.html.erb
<%= form_for @solicitation do |f| %>
  <div class="input-field">
    <%= f.label :subject, 'Assunto' %>
    <%= f.text_field :subject %>
  </div>
  <div class="input-field">
    <%= f.label :content, 'Descreva a solicitação' %>
    <%= f.text_area :content, class:'materialize-textarea' %>
  </div>
  <div class="input-field center-align">
    <%= f.submit 'Enviar Solicitação', class: 'btn' %>
  </div>
<% end %>

app/views/solicitations/_solicitation.html.erb
<ul class="collection with-header">
  <li class="collection-item active"><h6><%= 'Protocolo da solicitação: ' + solicitation.id.to_s %></h6></li>
  <li class="collection-item"><%= solicitation.subject %></li>
  <li class="collection-item"><%= solicitation.content %></li>
  <li class="collection-item"><%= link_to 'Alterar solicitação', edit_solicitation_path(solicitation) %></li>
</ul>
<br/>

app/views/solicitations/edit.html.erb
<%= render partial: 'form' %>

app/views/solicitations/new.html.erb
<h5 class="center-align card-panel red lighten-1 white-text">Nova Solicitação</h5>
<%= render partial: 'form' %>

app/views/solicitations/show.html.erb
<%= render @solicitation %>